# This file contains dictionaries containing the names of various DH maps.
# These are seperated into "Advance", "Push", "Clash", and "Armored" dicts
# to easily seperate and work with each game mode individually.

adv_dict = {
    "Battle In House"    : "DH-BattleInHouse_Advance",
    "Berezina"           : "DH-Berezina_Advance",
    "Black Day July"     : "DH-Black_Day_July_Advance",
    "Bridgehead"         : "DH-Bridgehead_Advance",
    "Butovo"             : "DH-Butovo_Advance",
    "Caen"               : "DH-Caen_Advance",
    "Carpiquet Airfield" : "DH-Carpiquet_Airfield_Advance",
    "Champs"             : "DH-Champs_Advance",
    "Cheneux"            : "DH-Cheneux_Advance",
    "Cholm"              : "DH-Cholm_Advance",
    "Dom Pavlova"        : "DH-Dom-Pavlova_Advance",
    "Haunted Fury"       : "DH-Haunted_Fury_Advance",
    "Hurtgenwald"        : "DH-Hurtgenwald_Advance",
    "Kasserine Pass"     : "DH-Kasserine_Pass_Advance",
    "Klin 1941"          : "DH-Klin1941_Advance",
    "Kommerscheidt"      : "DH-Kommerscheidt_Advance",
    "Kriegstadt"         : "DH-Kriegstadt_Advance",
    "La Cambe"           : "DH-La_Cambe_Advance",
    "La Fiere"           : "DH-La_Fiere_Advance",
    "La Fiere Day"       : "DH-La_Fiere_Day_Advance",
    "La Gleize"          : "DH-La_Gleize_Advance",
    "Makhnovo"           : "DH-Makhnovo_Advance",
    "Merderet"           : "DH-Merderet_Advance",
    "Myshkova River"     : "DH-MyshkovaRiver_Advance",
    "Noville"            : "DH-Noville_Advance",
    "Olkhovatka"         : "DH-Olkhovatka_Advance",
    "Oosterbeek"         : "DH-Oosterbeek_Advance",
    "Poteau Ambush"      : "DH-Poteau_Ambush_Advance",
    "Putot En Bessin"    : "DH-Putot-en-Bessin_Advance",
    "Rabenheck"          : "DH-Rabenheck_Advance",
    "Radar"              : "DH-Radar_Advance",
    "Rakowice"           : "DH-Rakowice_Advance",
    "Rederitz"           : "DH-Rederitz_Advance",
    "Reichswald"         : "DH-Reichswald_Advance",
    "Road To Isigny"     : "DH-Road_To_Isigny_Advance",
    "San Valentino"      : "DH-San_Valentino_Advance",
    "Schijndel"          : "DH-Schijndel_Advance",
    "Smolensk"           : "DH-Smolensk_Advance",
    "St Marie Du Mont"   : "DH-St_Marie_du_Mont_Advance",
    "Stoumont"           : "DH-Stoumont_Advance",
    "Valko"              : "DH-Valko_Advance",
    "Varaville"          : "DH-Varaville_Advance",
    "Wanne"              : "DH-Wanne_Advance"
}

push_dict = {
    "Bois Jacques"        : "DH-Bois_Jacques_Push",
    "Brecourt"            : "DH-Brecourt_Push",
    "Carentan Causeway"   : "DH-Carentan_Causeway_Push",
    "Carentan"            : "DH-Carentan_Push",
    "Chambois"            : "DH-Chambois_Push",
    "Cheneux"             : "DH-Cheneux_Push",
    "Danzig"              : "DH-Danzig_Push",
    "Dead Man's Corner"   : "DH-Dead_Man's_Corner_Push",
    "Dog Green"           : "DH-Dog_Green_Push",
    "Falaise"             : "DH-Falaise_Push",
    "Flakturm Tiergarten" : "DH-Flakturm_Tiergarten_Push",
    "Foucarville"         : "DH-Foucarville_Push",
    "Foy"                 : "DH-Foy_Push",
    "Ginkel Heath"        : "DH-Ginkel_Heath_Push",
    "Godolloi"            : "DH-Godolloi_Push",
    "Gorlitz"             : "DH-Gorlitz_Push",
    "GunAssault"          : "DH-GunAssault_Push",
    "Hill 108"            : "DH-Hill_108_Push",
    "Hill 400"            : "DH-Hill_400_Push",
    "House Of Horror"     : "DH-House_Of_Horror_Push",
    "Hurtgenwald"         : "DH-Hurtgenwald_Push",
    "Juno Beach"          : "DH-Juno_Beach_Push",
    "Konigsplatz"         : "DH-Konigsplatz_Push",
    "Kriegstadt"          : "DH-Kriegstadt_Push",
    "Kryukovo"            : "DH-Kryukovo_Push",
    "La Cambe"            : "DH-La_Cambe_Push",
    "La Chapelle"         : "DH-La_Chapelle_Push",
    "La Gleize"           : "DH-La_Gleize_Push",
    "Leningrad"           : "DH-Leningrad_Push",
    "Lutremange"          : "DH-Lutremange_Push",
    "Maupertus"           : "DH-Maupertus_Push",
    "Noville"             : "DH-Noville_Push",
    "Nyiregyhaza"         : "DH-Nyiregyhaza_Push",
    "Odessa"              : "DH-Odessa_Push",
    "Omaha Beach"         : "DH-OmahaBeach_Push",
    "Pariserplatz"        : "DH-Pariserplatz_Push",
    "Pointe Du Hoc"       : "DH-Pointe_Du_Hoc_Push",
    "Poteau Ambush"       : "DH-Poteau_Ambush_Push",
    "Prussia"             : "DH-Prussia_Push",
    "Raids"               : "DH-Raids_Push",
    "Rakowice"            : "DH-Rakowice_Push",
    "Ramelle"             : "DH-Ramelle_Push",
    "Red God Of War"      : "DH-Red_God_Of_War_Push",
    "Reichswald"          : "DH-Reichswald_Push",
    "Riga Docks"          : "DH-Riga_Docks_Push",
    "Simonskall"          : "DH-Simonskall_Push",
    "St Clement"          : "DH-St-Clement_Push",
    "Stalingrad Kessel"   : "DH-StalingradKessel_Push",
    "Stavelot"            : "DH-Stavelot_Push",
    "Stoumont"            : "DH-Stoumont_Push",
    "Targnon"             : "DH-Targnon_Push",
    "Tula Outskirts"      : "DH-TulaOutskirts_Push",
    "Turqueville"         : "DH-Turqueville_Push",
    "Vierville"           : "DH-Vierville_Push",
    "Vossenack"           : "DH-Vossenack_Push",
    "Zhitomir 1941"       : "DH-Zhitomir1941_Push"
}

clash_dict = {
    "Barashka"         : "DH-Barashka_Clash",
    "Cambes En Plaine" : "DH-Cambes-En-Plaine_Clash",
    "Fallen Heroes"    : "DH-FallenHeroes_Clash",
    "Fury"             : "DH-Fury_Clash",
    "Hattert"          : "DH-Hattert_Clash",
    "Haunted Hattert"  : "DH-Haunted_Hattert_Clash",
    "Hedgerow Hell"    : "DH-Hedgerow_Hell_Clash",
    "Lutremange"       : "DH-Lutremange_Clash",
    "Nuenen"           : "DH-Nuenen_Clash",
    "Olgedow"          : "DH-Ogledow_Clash",
    "Remagen"          : "DH-Remagen_Clash",
    "Rhine River"      : "DH-Rhine_River_Clash",
    "Salaca River"     : "DH-Salaca_River_Clash",
    "Ten Aard"         : "DH-Ten_Aard_Clash",
    "Winter Stalemate" : "DH-Winter_Stalemate_Clash"
}

arm_dict = {
    "Alte Ziegelei"          : "DH-Armored_AlteZiegelei_Stalemate",
    "Arad"                   : "DH-Armored_Arad_Clash",
    "Balaton"                : "DH-Armored_Balaton_Clash",
    "Bautzen"                : "DH-Armored_Bautzen_Clash",
    "Black Day July"         : "DH-Armored_Black_Day_July_Clash",
    "Brenus"                 : "DH-Armored_Brenus_Clash",
    "Cagny"                  : "DH-Armored_Cagny_Clash",
    "Celles"                 : "DH-Armored_Celles_Clash",
    "Debrecen"               : "DH-Armored_Debrecen_Clash",
    "Eindhoven"              : "DH-Armored_Eindhoven_Clash",
    "Freyneux"               : "DH-Armored_Freyneux_Advance",
    "Gran"                   : "DH-Armored_Gran_Advance",
    "Hill 112"               : "DH-Armored_Hill112_Advance",
    "Hunters Woods"          : "DH-Armored_Hunters_Woods_Clash",
    "Kasserine Pass"         : "DH-Armored_Kasserine_Pass_Advance",
    "Kharkov"                : "DH-Armored_Kharkov_Advance",
    "Kommerscheidt"          : "DH-Armored_Kommerscheidt_Clash",
    "Krivi Rog"              : "DH-Armored_KrivoiRog_Clash",
    "La Champagne"           : "DH-Armored_La_Champagne_Advance",
    "La Feuille"             : "DH-Armored_La_Feuillie_Clash",
    "La Monderie"            : "DH-Armored_La_Monderie_Clash",
    "Lemberg"                : "DH-Armored_Lemberg_Clash",
    "Mannikkala"             : "DH-Armored_Mannikkala_Clash",
    "Maslova"                : "DH-Armored_Maslova_Clash",
    "Mickistein"             : "DH-Armored_Mickistein_Clash",
    "Orel"                   : "DH-Armored_Orel_Clash",
    "Panzerschlacht"         : "DH-Armored_Panzerschlacht_Clash",
    "Preaux"                 : "DH-Armored_Preaux_Clash",
    "Raid To Bastogne"       : "DH-Armored_Raid_to_Bastogne_Advance",
    "Road To Leningrad"      : "DH-Armored_Road_to_Leningrad_Advance",
    "Studzianki"             : "DH-Armored_Studzianki_Clash",
    "Suedwind"               : "DH-Armored_Suedwind_Advance",
    "Tank Clash At Bastogne" : "DH-Armored_Tank_Clash_At_Bastogne_Advance",
    "Tractable"              : "DH-Armored_Tractable_Advance",
    "Voronezh"               : "DH-Armored_Voronezh_Clash"
}

def_dict = {
    "Flakturm Tiergarten" : "DH-Flakturm_Tiergarten_Defence",
    "Krasnyi Oktyabr"     : "DH-Krasnyi_Oktyabr_Defence",
    "Lyes Krovy"          : "DH-Lyes_Krovy_Defence"
}
