# This file contains a dictionary containing most-if-not-all DH weapons.
# Mainly here to keep other files clean, and to be reused in multiple commands.

# Not sorted in any particular order currently.
dh_weps = {
    '"DH_MG34DamType"'                  : "MG 34",
    '"DH_MP40DamType"'                  : "MP 40",
    '"DH_PPSH41DamType"'                : "PPSH-41 Drum",
    '"DH_DP28DamType"'                  : "DP 28",
    '"DH_30calDamType"'                 : "Browning M1919",
    '"DH_BARDamType"'                   : "BAR",
    '"DH_ThompsonDamType"'              : "Thompson SMG",
    '"DH_MG42DamType"'                  : "MG 42",
    '"DH_Kar98DamType"'                 : "Kar 98k",
    '"DH_M1GarandDamType"'              : "M1 Garand",
    '"DH_StenMkIIDamType"'              : "Sten Mk. II",
    '"DH_STG44DamType"'                 : "STG 44",
    '"DH_G43DamType"'                   : "Gewehr 43",
    '"DH_M1CarbineDamType"'             : "M1 Carbine",
    '"DH_GreaseGunDamType"'             : "M3 Grease Gun",
    '"DH_SVT40DamType"'                 : "SVT-40",
    '"DH_EnfieldNo4DamType"'            : "Enfield No.4",
    '"DH_PPD40DamType"'                 : "PPD-40",
    '"DH_M38DamType"'                   : "M 38",
    '"DH_BesaDamType"'                  : "Besa",
    '"DH_TT33DamType"'                  : "TT-33",
    '"DH_MN9130DamType"'                : "MN-9130",
    '"DH_BrenDamType"'                  : "Bren",
    '"DH_Winchester1897DamType"'        : "Winchester 1897",
    '"DH_PTRDDamType"'                  : "PTRD-41",
    '"DH_SpringfieldScopedDamType"'     : "Springfield M1903",
    '"DH_PPS43DamType"'                 : "PPS-43",
    '"DH_FG42DamType"'                  : "FG42",
    '"DH_Kar98ScopedDamType"'           : "Scoped Kar 98k",
    '"DH_50CalDamType"'                 : "50 Cal. MG",
    '"DH_P38DamType"'                   : "Walther P38",
    '"DH_G41DamType"'                   : "Gewehr 41",
    '"DH_G43ScopedDamType"'             : "Scoped Gewehr 43",
    '"DH_MP41DamType"'                  : "MP41",
    '"DH_ColtM1911DamType"'             : "Colt M1911",
    '"DH_C96DamType"'                   : "Mauser C96",
    '"DH_PPSH41_stickDamType"'          : "PPSH-41 35rnd",
    '"DH_EnfieldNo2DamType"'            : "Enfield No.2",
    '"DH_AVT40DamType"'                 : "AVT-40",
    '"DH_Nagant1895DamType"'            : "Nagant 1895",
    '"DH_M44DamType"'                   : "MN-M44 Carbine",
    '"DH_MN9130ScopedDamType"'          : "Scoped MN-9130",
    '"DH_BazookaImpactDamType"'         : "Bazooka",
    '"DH_PanzerschreckImpactDamType"'   : "Panzerschreck",
    '"DH_PanzerFaustImpactDamType"'     : "Panzerfaust",
    '"DH_StielGranateDamType"'          : "Stielhandgranate",
    '"DH_F1GrenadeDamType"'             : "F1 Grenade",
    '"DH_M1GrenadeDamType"'             : "M1 Grenade",
    '"DHShellHE75mmDamageType"'         : "75mm HE",
    '"DHShellHE75mmATDamageType"'       : "75mm HEAT",
    '"DHArtillery105DamageType"'        : "Artillery 105mm",
    '"DHShellHE105mmDamageType"'        : "105mm HE",
    '"DHShellHE37mmDamageType"'         : "37mm HE",
    '"DHShellHE50mmATDamageType"'       : "50mm HEAT",
    '"DHShellAPGunImpactDamageType"'    : "AP Shell",
    '"DHShellImpactDamageType"'         : "Shell Impact"
}
